import { jsPDF } from 'jspdf'

export function exportReferralPDF(patient, riskResult, referralLetter) {
  const doc = new jsPDF()
  
  // Colors
  const RED = [198, 40, 40]
  const NAVY = [26, 35, 126]
  const GRAY = [100, 100, 100]
  
  // Header
  doc.setFontSize(24)
  doc.setTextColor(...RED)
  doc.setFont(undefined, 'bold')
  doc.text('MOTHERSHIELD', 20, 20)
  
  doc.setFontSize(16)
  doc.setTextColor(...NAVY)
  doc.text('Maternal Risk Referral Letter', 20, 30)
  
  // Date aligned right
  doc.setFontSize(11)
  doc.setTextColor(...GRAY)
  doc.setFont(undefined, 'normal')
  const today = new Date().toLocaleDateString()
  doc.text(`Date: ${today}`, 190, 30, { align: 'right' })
  
  // Horizontal line
  doc.setDrawColor(...GRAY)
  doc.line(20, 35, 190, 35)
  
  let yPos = 45
  
  // Patient Details Section
  doc.setFontSize(12)
  doc.setTextColor(...NAVY)
  doc.setFont(undefined, 'bold')
  doc.text('Patient Details', 20, yPos)
  yPos += 8
  
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.setFont(undefined, 'normal')
  const patientDetails = [
    ['Name:', patient.name || 'N/A'],
    ['Age:', `${patient.age} years`],
    ['Gestational Weeks:', `${patient.gestationalWeeks} weeks`],
    ['Previous Births:', `${patient.previousBirths}`],
    ['Previous Complications:', patient.previousComplications || 'None']
  ]
  
  patientDetails.forEach((row) => {
    doc.text(`${row[0]}`, 25, yPos)
    doc.text(`${row[1]}`, 80, yPos)
    yPos += 6
  })
  
  yPos += 4
  
  // Vitals Section
  doc.setFontSize(12)
  doc.setTextColor(...NAVY)
  doc.setFont(undefined, 'bold')
  doc.text('Vital Signs', 20, yPos)
  yPos += 8
  
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.setFont(undefined, 'normal')
  const vitals = [
    [`Systolic BP: ${patient.systolicBP} mmHg`, `Diastolic BP: ${patient.diastolicBP} mmHg`],
    [`Hemoglobin: ${patient.hemoglobin} g/dL`, `Body Temperature: ${patient.bodyTemp}°C`]
  ]
  
  vitals.forEach((row) => {
    doc.text(row[0], 25, yPos)
    doc.text(row[1], 110, yPos)
    yPos += 6
  })
  
  yPos += 4
  
  // Risk Assessment Section
  doc.setFontSize(12)
  doc.setTextColor(...NAVY)
  doc.setFont(undefined, 'bold')
  doc.text('Risk Assessment', 20, yPos)
  yPos += 8
  
  const riskColor = riskResult?.riskLevel === 'CRITICAL' ? [183, 28, 28] : 
                    riskResult?.riskLevel === 'HIGH' ? [230, 81, 0] :
                    riskResult?.riskLevel === 'MEDIUM' ? [245, 127, 23] : [27, 94, 32]
  
  doc.setFontSize(14)
  doc.setTextColor(...riskColor)
  doc.setFont(undefined, 'bold')
  doc.text(`Risk Level: ${riskResult?.riskLevel || 'UNKNOWN'}`, 25, yPos)
  yPos += 8
  
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.setFont(undefined, 'normal')
  const explanation = riskResult?.explanation || 'No explanation provided'
  const explLines = doc.splitTextToSize(explanation, 160)
  doc.text(explLines, 25, yPos)
  yPos += explLines.length * 5 + 4
  
  // Referral Letter Section
  if (referralLetter) {
    doc.setFontSize(12)
    doc.setTextColor(...NAVY)
    doc.setFont(undefined, 'bold')
    doc.text('Referral Letter', 20, yPos)
    yPos += 8
    
    doc.setFontSize(10)
    doc.setTextColor(0, 0, 0)
    doc.setFont(undefined, 'normal')
    const letterLines = doc.splitTextToSize(referralLetter, 160)
    doc.text(letterLines, 25, yPos)
    yPos += letterLines.length * 4
  }
  
  // Footer
  doc.setFontSize(9)
  doc.setTextColor(...GRAY)
  doc.text('Generated by MotherShield AI — For medical professional use only', 105, 280, { align: 'center' })
  
  doc.save('MotherShield_Referral.pdf')
}

export function exportDangerSignsCard(patient, riskResult) {
  const doc = new jsPDF('landscape', 'mm', 'a5')
  
  const RED = [198, 40, 40]
  const NAVY = [26, 35, 126]
  
  // Title
  doc.setFontSize(18)
  doc.setTextColor(...RED)
  doc.setFont(undefined, 'bold')
  doc.text('DANGER SIGNS CARD', 10, 15)
  
  // Patient Info
  doc.setFontSize(11)
  doc.setTextColor(...NAVY)
  doc.setFont(undefined, 'bold')
  doc.text(`Patient: ${patient.name || 'N/A'}`, 10, 25)
  doc.text(`Age: ${patient.age || 'N/A'} | Date: ${new Date().toLocaleDateString()}`, 10, 32)
  
  // Danger Signs
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.setFont(undefined, 'bold')
  doc.text('Danger Signs to Watch For:', 10, 42)
  
  doc.setFontSize(9)
  doc.setFont(undefined, 'normal')
  const complications = riskResult?.complications || ['Severe headache', 'Visual disturbances', 'Severe abdominal pain', 'Vaginal bleeding']
  
  let yPos = 50
  complications.forEach((comp, idx) => {
    doc.text(`${idx + 1}. ${comp}`, 15, yPos)
    yPos += 7
  })
  
  // Emergency Info
  doc.setFontSize(14)
  doc.setTextColor(...RED)
  doc.setFont(undefined, 'bold')
  doc.text('EMERGENCY: Call 108 Immediately', 105, 60, { align: 'center' })
  
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.setFont(undefined, 'normal')
  doc.text('If any danger signs appear, seek immediate medical attention', 105, 70, { align: 'center' })
  
  doc.save('MotherShield_DangerSigns.pdf')
}
